### ISSUE TITLE
FVTT Version 10 Build 284 Compatibility

### ISSUE THREAD

**Issue by CharlesHunter** [League-of-Foundry-Developers/fvtt-module-lmrtfy#159]
Upon clicking the "Request Roll" button while logged in as a GM, the following exception is thrown.
```
TypeError: key.split is not a function or its return value is not iterable
[Detected 1 package: lmrtfy]
    at Object.getProperty (commons.js:1698:24)
    at Localization.localize (foundry.js:6689:27)
    at requestor.js:51:39
    at Array.sort (<anonymous>)
    at LMRTFYRequestor.getData (requestor.js:51:14)
    at LMRTFYRequestor._render (foundry.js:4959:29)
    at LMRTFYRequestor._render (foundry.js:5684:17)
    at LMRTFYRequestor.render (foundry.js:4918:10)
    at LMRTFYRequestor.render (requestor.js:83:22)
    at LMRTFY.requestRoll (lmrtfy.js:221:26)
    at Object.onClick (lmrtfy.js:245:39)
    at SceneControls._onClickTool (foundry.js:66673:52)
    at HTMLLIElement.dispatch (jquery.min.js:2:43064)
    at y.handle (jquery.min.js:2:41048)
```

**Comment by vtt-lair** [comment]
Yeah, compatible core version is till only 9 so it won't work in version 10 at all. I'm busy with the testing of the version 10 changes at should hopefully be available later this weekend.
