### ISSUE TITLE
Console error when selecting the lmrtfy button after v10 update

### ISSUE THREAD

**Issue by KaikanPanda** [League-of-Foundry-Developers/fvtt-module-lmrtfy#162]
I am getting this error in the console when selecting the lmrtfy button in any scene. This was working fine last week prior to upgrading to v10. 

**CONSOLE ERROR:**
Foundry VTT | Rendering LMRTFYRequestor
foundry.js:711 TypeError: key.split is not a function or its return value is not iterable
[Detected 1 package: lmrtfy]
    at Object.getProperty (commons.js:1698:24)
    at Localization.localize (foundry.js:6689:27)
    at requestor.js:51:39
    at Array.sort (<anonymous>)
    at LMRTFYRequestor.getData (requestor.js:51:14)
    at LMRTFYRequestor._render (foundry.js:4959:29)
    at LMRTFYRequestor._render (foundry.js:5684:17)
    at LMRTFYRequestor.render (foundry.js:4918:10)
    at LMRTFYRequestor.render (requestor.js:85:22)
    at LMRTFY.requestRoll (lmrtfy.js:257:26)
    at Object.onClick (lmrtfy.js:281:39)
    at SceneControls._onClickTool (foundry.js:66673:52)
    at HTMLLIElement.dispatch (jquery.min.js:2:43064)
    at y.handle (jquery.min.js:2:41048)

**Foundry support details:**
Foundry Virtual Tabletop: Version 10, 10.284
Game System: dnd5e, 2.0.2
Active Modules: 4
Performance Mode: 2

OS: Unknown
Client: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36
GPU: ANGLE (Apple, Apple M1, OpenGL 4.1)
Max Texture Size: 16384

Scene: 6000 x 4600 | Grid Size: 100 | Padding Percentage: 0.25
Walls: 0 | Ambient Lights: 0 | Ambient Sounds: 0 | Tiles: 0 | Tokens: 1

Actors: 222 | Items: 2624 | Journal: 414 | Rollable Tables: 13 |
Playlists: 2 | Compendium Packs: 28 | Chat Messages: 3130

**Comment by imobe001** [comment]
I am having the same issue.  Here is the error statement:

foundry.js:711 TypeError: An error occurred while rendering LMRTFYRequestor 55. key.split is not a function or its return value is not iterable
    at Object.getProperty (commons.js:1698:24)
    at Localization.localize (foundry.js:6689:27)
    at requestor.js:51:39
    at Array.sort (<anonymous>)
    at LMRTFYRequestor.getData (requestor.js:51:14)
    at LMRTFYRequestor._render (foundry.js:4959:29)
    at LMRTFYRequestor._render (foundry.js:5684:17)
    at LMRTFYRequestor.render (foundry.js:4918:10)
    at LMRTFYRequestor.render (requestor.js:85:22)
    at LMRTFY.requestRoll (lmrtfy.js:257:26)

**Comment by Varriount** [comment]
Currently LMRTFY hasn't been updated to work with v10 - if someone wants to open a pull request to add v10 compatibility, I'll happily review it. Otherwise, I don't know when I'll get around to it.

**Comment by vtt-lair** [comment]
@KaikanPanda, @imobe001 busy getting a fix for this into the module. A change was made to DnD 5e's system that is causing this to break. New fixed version should be out later today.

Please note that this _is_ indeed for version 10 and was working with version 10 until the DnD system change.
