### ISSUE TITLE
PF1E Error on Ability Checks

### ISSUE THREAD

**Issue by KitCat420** [League-of-Foundry-Developers/fvtt-module-lmrtfy#192]
Rolling any ability check in PF1E will trigger the following error in the console and the roll will fail:
```
Uncaught (in promise) TypeError: undefined. Cannot read properties of undefined (reading 'call')
[Detected 1 package: lmrtfy]
    at LMRTFYRoller._makeRoll (roller.js:328:45)
    at LMRTFYRoller._onAbilityCheck (roller.js:489:18)
    at HTMLButtonElement.dispatch (jquery.min.js:2:43184)
    at y.handle (jquery.min.js:2:41168)
_
```

**Comment by KitCat420** [comment]
Duplicate of #166
